//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadSafeRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnsafeTable
    {
        public int MRIID { get; set; }
        public int ImagePageCount { get; set; }
        public int ImageFileSize { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime DelayedDatetime { get; set; }
    }
}
